/**
 * Edit semantic token values in this file. Run
 * `pnpm --filter @pebtech/tokens run build` to regenerate
 * `packages/tokens/dist/css/tokens.css` AND the consumed copy at
 * `packages/ui-web/src/styles/tailwind.css`. Do not hand-edit the generated
 * CSS files — they are overwritten on every build.
 */
import type { SemanticTokens } from './types'
import { neutral, brand, status, statusBg, statusBorder } from './colors'

export const lightTokens: SemanticTokens = {
  text: {
    white: '#ffffff',
    black: '#000000',
    brand: brand.default,
    brandAlt: brand.alt,
    primary: neutral[900],
    secondary: neutral[600],
    tertiary: neutral[500],
    quaternary: neutral[400],
    muted: neutral[500],
    disabled: neutral[400],
    inverse: '#ffffff',
    link: '#2563eb',
    error: status.error.light,
    success: status.success.light,
    warning: status.warning.light,
    info: status.info.light,
    pending: status.pending.light,
    page: neutral[900],
    surface: neutral[900],
    border: neutral[200],
  },
  bg: {
    brand: brand.default,
    body: '#EFEFEB',
    bodySecondary: '#FAFBF8',
    formPage: '#EFEFEB',
    primary: '#ffffff',
    secondary: neutral[50],
    tertiary: neutral[100],
    quaternary: neutral[200],
    surface: '#ffffff',
    inverse: neutral[900],
    overlay: 'rgba(0, 0, 0, 0.4)',
    error: statusBg.error.light,
    success: statusBg.success.light,
    warning: statusBg.warning.light,
    info: statusBg.info.light,
    pending: statusBg.pending.light,
    sidebar: '#EFEFEB',
    sidebarSecondary: '#FAFBF8',
    tableHeader: neutral[100],
  },
  border: {
    brand: brand.default,
    primary: neutral[200],
    secondary: neutral[100],
    focus: brand.default,
    error: statusBorder.error.light,
    success: statusBorder.success.light,
    warning: statusBorder.warning.light,
    info: statusBorder.info.light,
    pending: statusBorder.pending.light,
  },
  hover: {
    brand: brand.alt,
    primary: neutral[100],
    secondary: neutral[400],
    tertiary: neutral[500],
    white: neutral[600],
    surface: neutral[50],
    surfaceActive: neutral[100],
    black: neutral[800],
    page: status.error.dark,
    muted: status.success.light,
    inverse: status.warning.light,
    link: '#1d4ed8',
    error: '#b91c1c',
    success: '#15803d',
    disabled: neutral[300],
  },
  focus: {
    primary: brand.default,
    secondary: '#2563eb',
    error: status.error.light,
    success: status.success.light,
    warning: status.warning.light,
    info: status.info.light,
    pending: status.pending.light,
  },
  input: {
    default: '#ffffff',
    hover: neutral[100],
    active: neutral[100],
    focus: neutral[100],
    error: statusBg.error.light,
    success: statusBg.success.light,
    warning: statusBg.warning.light,
    info: statusBg.info.light,
    pending: statusBg.pending.light,
    disabled: neutral[100],
  },
}

export const darkTokens: SemanticTokens = {
  text: {
    white: '#ffffff',
    black: '#000000',
    brand: brand.light,
    brandAlt: brand.default,
    primary: neutral[50],
    secondary: neutral[400],
    tertiary: neutral[500],
    quaternary: neutral[600],
    muted: neutral[500],
    disabled: neutral[600],
    inverse: neutral[900],
    link: '#60a5fa',
    error: status.error.dark,
    success: status.success.dark,
    warning: status.warning.dark,
    info: status.info.dark,
    pending: status.pending.dark,
    page: neutral[50],
    surface: neutral[50],
    border: neutral[700],
  },
  bg: {
    brand: brand.default,
    body: neutral[950],
    bodySecondary: neutral[900],
    formPage: neutral[950],
    primary: neutral[900],
    secondary: neutral[800],
    tertiary: neutral[700],
    quaternary: neutral[600],
    surface: neutral[800],
    inverse: neutral[100],
    overlay: 'rgba(0, 0, 0, 0.7)',
    error: statusBg.error.dark,
    success: statusBg.success.dark,
    warning: statusBg.warning.dark,
    info: statusBg.info.dark,
    pending: statusBg.pending.dark,
    sidebar: neutral[900],
    sidebarSecondary: neutral[800],
    tableHeader: neutral[800],
  },
  border: {
    brand: brand.default,
    primary: neutral[700],
    secondary: neutral[800],
    focus: brand.light,
    error: statusBorder.error.dark,
    success: statusBorder.success.dark,
    warning: statusBorder.warning.dark,
    info: statusBorder.info.dark,
    pending: statusBorder.pending.dark,
  },
  hover: {
    brand: brand.light,
    primary: neutral[800],
    secondary: neutral[600],
    tertiary: neutral[600],
    white: neutral[500],
    surface: neutral[800],
    surfaceActive: neutral[100],
    black: neutral[100],
    page: '#fca5a5',
    muted: status.success.dark,
    inverse: status.warning.dark,
    link: '#93c5fd',
    error: status.error.dark,
    success: status.success.dark,
    disabled: neutral[600],
  },
  focus: {
    primary: brand.light,
    secondary: '#60a5fa',
    error: status.error.dark,
    success: status.success.dark,
    warning: status.warning.dark,
    info: status.info.dark,
    pending: status.pending.light,
  },
  input: {
    default: neutral[900],
    hover: neutral[800],
    active: neutral[800],
    focus: neutral[800],
    error: statusBg.error.dark,
    success: statusBg.success.dark,
    warning: statusBg.warning.dark,
    info: statusBg.info.dark,
    pending: statusBg.pending.dark,
    disabled: neutral[800],
  },
}
